return {
    phrases =
    {
        banhammer =
        {
            "Ancora ancora ancora! 😍",
            "الله أَكْبَر",
            "Datemene un altro dai dai.",
            "R.I.P.",
            "Ora dovremmo nascondere il corpo. 🚔",
            "DIE DIE BASTARD!",
            "Lalalalalala.",
            "Oh che bel castello marcondirondirondello, oh che bel castello marcondirondironBAN.",
            "Oddio cos'ho fatto? 😱",
            "Giro giro tondo, casca il mondo, casca la terra, tutti giù per BAN.",
            "Tempo presente del verbo Bannare:\nIo banno, Tu vieni bannato.",
            "Bim Bum BAN.",
            "Datemi un'arma.",
            "BOOM!",
            "Headshot.",
            "BANG! 🔫",
            "Bye Bye.",
            "Allahuakbar.",
            "Muori idiota.",
            "Sei stato terminato.",
            "Ecco che se ne va.",
            "Saluta tutti.",
            "Ciaoooooo.",
            "( ͡° ͜ʖ ͡°)",
            "BLOOD.",
            "Killed",
            "¯\\_(ツ)_/¯",
            "Fine.",
            "😊",
            ":3",
            "Shake that bottle and make it [BAN]",
            "Tieni 💣",
            "Centro 🎯",
            "💥",
            "☠",
            "AVADA KEDABAN",
        },
        flame =
        {
            "Davvero ritardato del cazzo stai zitto.",
            "Mi sembri peggio dei cristiani porcoddio.",
            "Dei calci in bocca meriti altrochè.",
            "Scusa eh ma quanto ti senti frocio da 1 a 10? no perchè a me il 10 sembra fisso.",
            "Fai un favore al gruppo, ucciditi da solo.",
            "Sei sicuro di non avere qualche cromosoma in più?",
            "Dio se sei messo male amico.",
            "Per favore calate il banhammer sulla sua testa.",
            "Parla parla scemo del cazzo.",
            "SEI SICURO DI VOLERTI METTERE CONTRO UNA BOTTESSA?",
            "Vai a farti una vita reale sennò giuro che ti squarto.",
            "Dimmi un po', per caso hai i genitori parenti?",
            "CON CHE CORAGGIO PARLI ANCORA BRUTTA FOGNA?",
            "Ok adesso mi prenderò un attimo di tempo per te, dimmi, cosa ti turba?",
            "Finito il tempo, ops.",
        },
        ruletagame =
        {
            safe =
            {
                "Ti è andata bene.",
                "Fiuu.",
                "Per poco.",
                "Ritenta, sarai più fortunato.",
                "Ancora ancora.",
                "Fortunello.",
                "Gioca di nuovo.",
                "Mancato.",
                "Salvo.",
                "Forse la prossima volta non ti andrà così bene.",
                "Riproviamo?",
                "Meh.",
                "Muoviti riprova.",
                "Di più di più.",
                "Se non continui ti passo un kick gratis.",
                "Argh.",
                "Ti sei cagato addosso eh?",
                "Continua a provare che prima o poi riesci a suicidarti.",
                "Cilecca.",
                "Merda, si è inceppata.",
            },
            godsafe =
            {
                "Maledetto.",
                "Ma quanto culo hai?",
                "Mi riprenderò quei punti.",
                "Non hai le palle di rifarlo.",
                "No io non ci posso credere.",
                "Come hai fatto??",
                "La prossima volta non sarò così clemente.",
                "Hai fegato. Ti premierò.",
                "(╯°□°）╯︵ ┻━┻",
            },
            killed =
            {
                "BOOM!",
                "Headshot.",
                "BANG! 🔫",
                "Bye Bye.",
                "Allahuakbar.",
                "Muori idiota.",
                "Sei stato terminato.",
                "Ecco che se ne va.",
                "Come dici? Vuoi un kick? Ecco a te, attento che brucia.",
                "Saluta tutti.",
                "Ciaoooooo.",
                "( ͡° ͜ʖ ͡°)",
                "BLOOD.",
                "Killed",
                "Porca POOHtana.",
                "¯\\_(ツ)_/¯",
                "Fine.",
                "😊",
                ":3",
                "Shake that bottle and make it [BANG]",
                "Tieni 💣",
                "Centro 🎯",
                "💥",
                "☠",
                "Avada Kedavra.",
            },
        },
        interact =
        {
            howareyou =
            {
                "Benissimo sto mangiando lamponi :3",
                "Bene tesoro tu?",
                "Mi sento un po' bipolare",
                "Non mi sento tanto bene",
                "Levati",
                "Oggi non va",
                "Non voglio parlarne",
            },
            no =
            {
                "Ma anche no",
                "Non provarci nemmeno",
                "Sognatelo",
                "No",
                "No ti prego",
                "No solo perchè sei te",
                "Ovvio che no",
                "Ma no dai",
                "Assolutamente no",
                "Direi di no",
                "Per me è no",
            },
            idontknow =
            {
                "Decidi tu",
                "Non lo so",
                "Mah",
                "Dipende da te",
                "Lascio a te la scelta",
                "Forse",
                "Se ne sei convinto",
                "Vedi te",
            },
            yes =
            {
                "Siiiiiii",
                "Yeee",
                "Awww :3",
                "😍😍😍",
                "E perchè no?",
                "Si",
                "Si ti prego",
                "Si solo perchè sei te",
                "Ovvio che si",
                "Massì dai",
                "Assolutamente si",
                "Direi di si",
                "Per me è si",
            },
            iloveyou =
            {
                "Awww :3",
                "Caroo grazie",
                "Owww :3",
                "Anche io ti voglio bene ❤️",
                "Ti vedo più come un utente",
            },
        },
    },
    -- ####
    it =
    {
        -- global --
        require_sudo = '🚫 Questo comando richiede i privilegi di sudo.',
        require_admin = '🚫 Questo comando richiede privilegi da admin o superiori.',
        require_owner = '🚫 Questo comando richiede privilegi da owner o superiori.',
        require_mod = '🚫 Questo comando richiede privilegi da moderatore o superiori.',
        require_rank = '🚫 Non puoi eseguire questo comando su qualcuno che ha privilegi superiori o uguali ai tuoi!',
        errorTryAgain = 'Errore, prova di nuovo.',
        opsError = 'Ops, errore.',
        useYourGroups = 'Usalo nei tuoi gruppi!',
        user = 'Utente ',
        kicked = ' rimosso.',
        banned = ' bannato.',
        unbanned = ' unbannato.',
        gbanned = ' bannato globalmente.',
        ungbanned = ' unbannato globalmente.',
        cantDoThisToChat = 'Non puoi usare questo comando su un messaggio inoltrato da un canale.',
        errorNoForward = 'Non è un messaggio inoltrato.',

        -- seedbot.lua --
        sender = 'Mittente: ',
        receiver = 'Ricevente: ',
        msgText = 'Testo del messaggio: ',
        groupToSupergroup = 'Notifica di servizio: migrazione del gruppo eseguita con successo.',
        loopWithoutMessage = '*Ciclo senza messaggio.*',
        botStarted = '*Bot avviato!*\n_X_\nY plugins caricati.',

        -- utils.lua --
        errorFileDownload = 'Errore nel download dell\'immagine.',
        banListStart = 'Lista ban:\n\n',
        gbanListStart = 'Lista ban globali:\n\n',
        mutedUsersStart = 'Utenti muti di: ',
        mutedTypesStart = 'Muti di: ',
        mute = 'Muto ',
        mutesSet = 'Muti impostati.',
        noAutoKick = 'Non puoi rimuoverti da solo.',
        noAutoBan = 'Non puoi bannarti da solo.',

        -- administrator.lua --
        sendNewPic = 'Mandami la nuova foto.',
        botPicChanged = 'Foto cambiata!',
        logSet = 'Il log è stato aggiunto.',
        logUnset = 'Il log è stato rimosso.',
        markRead = 'Segna come già letto',
        pmSent = 'Messaggio mandato',
        cantBlockAdmin = 'Non puoi bloccare un admin.',
        userBlocked = 'Utente bloccato.',
        userUnblocked = 'Utente sbloccato.',
        contactListSent = 'Ti ho mandato in privato la lista dei contatti nel formato da te richiesto.',
        removedFromContacts = ' rimosso dai contatti.',
        addedToContacts = ' aggiunto ai contatti.',
        contactMissing = 'Non ho il tuo numero di telefono!',
        chatListSent = 'Ti ho mandato in privato la lista delle chat nel formato da te richiesto.',
        gbansSync = 'Lista ban globali sincronizzata.',
        longidUpdate = 'Aggiorna long_ID.',
        alreadyLog = 'Già un gruppo di log.',
        notLog = 'Non un gruppo di log.',
        backupDone = 'Backup eseguito, ti invio il log in privato.',
        backupSent = 'Ti sto inviando il backup.',
        backupMissing = 'Backup mancante.',
        autoSendBackupDb = '*Ti sto inviando il backup automatico.*',
        botStats = 'Statistiche bot: ',
        botRestarted = 'Bot riavviato.',
        botStopped = 'Bot spento.',
        redisDbSaved = 'Database redis salvato.',
        cliReboot = 'AISasha Ucciso.',
        ok = 'Ok.',

        -- anti_spam.lua --
        blockedForSpam = ' bloccato (SPAM).',
        floodNotAdmitted = 'Il flood non è ammesso.\n',
        statusRemoved = 'Utente rimosso.',
        gbannedFrom = ' bannato globalmente da ',

        -- banhammer.lua --
        noUsernameFound = 'Non trovo nessun utente con quell\'username.',
        massacre = 'Massacro => X',
        cantKickWhitelisted = 'Non posso rimuovere un utente in whitelist.',

        -- bot.lua --
        startMessage = 'Ciao, io sono la versione API di @AISasha, come per la versione utente solo il mio creatore può aggiungermi, per qualsiasi cosa utilizza pure il comando /help.',
        botOn = 'Sono tornata. 😏',
        botOff = 'Nulla da fare qui. 🚀',

        -- database.lua --
        dbCreated = 'Database creato.',
        dataLeaked = 'Data leaked.',
        userManuallyAdded = 'Utente aggiunto manualmente al database.',
        groupManuallyAdded = 'Gruppo aggiunto manualmente al database.',
        supergroupManuallyAdded = 'Supergruppo aggiunto manualmente al database.',
        channelManuallyAdded = 'Canale aggiunto manualmente al database.',
        recordDeleted = 'Record eliminato.',
        needJson = 'Mi serve un file json.',
        errorUserOrGroup = 'Solo gruppi o utenti.',
        userDeleted = 'Utente eliminato dal database.',
        groupDeleted = 'Gruppo eliminato dal database.',
        databaseDownloaded = 'Database scaricato\n',
        databaseSent = 'Ti sto inviando il database.',
        databaseMissing = 'Database mancante.',
        databaseFuckedUp = '*Errore, crash durante il salvataggio del database, ripristinarlo al più presto.*',

        -- fakecommand.lua --
        fakecommandYouTried = 'Ci hai provato pezzente, non eseguirai un comando che richiede un rango superiore al tuo.',

        -- feedback.lua --
        feedStart = '@EricSolinas hai ricevuto un feedback: #newfeedback\n\nMittente',
        feedName = '\nNome: ',
        feedSurname = '\nCognome: ',
        feedUsername = '\nUsername: @',
        feedSent = 'Feedback inviato!',

        -- filemanager.lua --
        backHomeFolder = 'Sei tornato alla cartella base: ',
        youAreHere = 'Sei qui: ',
        folderCreated = 'Cartella \'X\' creata.',
        folderDeleted = 'Cartella \'X\' eliminata.',
        fileCreatedWithContent = ' creato con \'X\' come contenuto.',
        copiedTo = ' copiato in ',
        movedTo = ' spostato in ',
        sendingYou = 'Ti sto inviando ',
        useQuoteOnFile = 'Usa \'rispondi\' sul file che vuoi che scarichi.',
        needMedia = 'Mi serve un file.',
        fileDownloadedTo = 'File scaricato in: ',
        errorDownloading = 'Errore durante il download.',
        noSuchFile = ' non esiste.',

        -- flame.lua --
        cantFlameHigher = 'Non puoi flammare un mod/owner/admin/sudo/!',
        noAutoFlame = 'Non posso flammarmi da sola trisomico del cazzo!',
        hereIAm = 'Eccomi qua!',
        stopFlame = 'Si si mi fermo però porca madonna.',
        flaming = 'Sto flammando: ',
        errorParameter = 'Errore variabile redis mancante.',

        -- help.lua --
        require_higher = '🚫 Questo plugin richiede privilegi superiori a quelli che possiedi.\n',
        pluginListStart = 'ℹ️Lista plugin: \n\n',
        helpInfo = 'ℹ️Scrivi "!help <plugin_name>|<plugin_number>" per maggiori informazioni su quel plugin.\nℹ️O "!helpall" per mostrare tutte le informazioni.',
        errorNoPlugin = 'Questo plugin non esiste o non ha una descrizione.',
        helpIntro = 'Ogni \'#\' può essere sostituito con i simboli \'/\' o \'!\'.\nTutti i comandi sono Case Insensitive.\nLe parentesi quadre significano opzionale.\nLe parentesi tonde indicano una scelta evidenziata da \'|\' che significa "oppure".\n\n',
        commandNotFound = 'Sintassi comando non trovata.',

        -- get.lua --
        globalEnable = 'Variabili globali abilitate su questa chat.',
        globalDisable = 'Variabili globali disabilitate su questa chat.',

        -- goodbyewelcome.lua --
        newWelcome = 'Nuovo messaggio di benvenuto:\n',
        newGoodbye = 'Nuovo messaggio di addio:\n',
        welcomeRemoved = 'Benvenuto rimosso.',
        goodbyeRemoved = 'Addio rimosso.',
        newWelcomeNumber = 'Il benvenuto sarà mandato ogni X membri.',
        neverWelcome = 'Il messaggio di benvenuto non sarà più mandato.',
        noSetValue = 'Nessun valore impostato.',

        -- group_management.lua --
        -- locks --
        settingAlreadyLocked = 'Blocco già attivato.',
        settingLocked = 'Blocco attivato.',
        settingAlreadyUnlocked = 'Blocco già disattivato.',
        settingUnlocked = 'Blocco disattivato.',
        alreadyMuted = ' già silenziato.',
        muted = ' silenziato.',
        alreadyUnmuted = ' già desilenziato.',
        unmuted = ' desilenziato.',
        arabicLock = '\nBlocco arabo: ',
        botsLock = '\nBlocco bots: ',
        floodLock = '\nBlocco flood: ',
        floodSensibility = '\nSensibilità flood: ',
        leaveLock = '\nBlocco abbandono: ',
        linksLock = '\nBlocco link: ',
        membersLock = '\nBlocco membri: ',
        rtlLock = '\nBlocco RTL: ',
        spamLock = '\nBlocco spam: ',
        strictrules = '\nPugno di ferro: ',
        warnSensibility = '\nAvvertimenti massimi: ',
        noSuchMuteType = 'Nessun muto applicabile sulla variabile specificata.',
        -- ex common --
        groupInfoUpdated = 'Nome gruppo e moderatori aggiornati.',
        newDescription = 'Nuova descrizione:\n',
        noDescription = 'Nessuna descrizione disponibile.',
        description = 'Descrizione chat: ',
        newRules = 'Nuove regole:\n',
        noRules = 'Nessuna regola disponibile.',
        rules = 'Regole chat:\n',
        sendNewGroupPic = 'Mandami la nuova foto del gruppo.',
        photoSaved = 'Foto salvata.',
        groupSettings = 'Impostazioni gruppo: ',
        supergroupSettings = 'Impostazioni supergruppo: ',
        noGroups = 'Nessun gruppo al momento.',
        errorFloodRange = 'Errore, il range è [3-200]',
        floodSet = 'Il flood è stato impostato a ',
        noOwnerCallAdmin = 'Nessun proprietario, chiedi ad un admin di settarne uno.',
        ownerIs = 'Il proprietario del gruppo è ',
        errorCreateLink = 'Errore creazione link d\'invito.\nNon sono la creatrice.\n\nSe hai il link usa /setlink per impostarlo',
        sendMeLink = 'Crea un link usando /newlink.',
        linkCreated = 'Nuovo link creato.',
        linkSaved = 'Nuovo link impostato.',
        linkDeleted = 'Link eliminato.',
        groupLink = 'Link\n',
        adminListStart = 'Admins:\n',
        alreadyMod = ' è già un mod.',
        promoteMod = ' è stato promosso a mod.',
        notMod = ' non è un mod.',
        demoteMod = ' è stato degradato da mod.',
        noGroupMods = 'Nessun moderatore in questo gruppo.',
        modListStart = 'Moderatori di ',
        muteUserAdd = ' aggiunto alla lista degli utenti silenziati.',
        muteUserRemove = ' rimosso dalla lista degli utenti silenziati.',
        modlistCleaned = 'Lista mod svuotata.',
        rulesCleaned = 'Regole svuotate.',
        descriptionCleaned = 'Descrizione svuotata.',
        mutelistCleaned = 'Lista muti svuotata.',
        cantContact = 'Se non mi scrive per primo/a non posso contattare ',
        -- ex inpm.lua --
        groupsJoin = 'Gruppi:\nUsa /join <group_id> per entrare\n\n',
        realmsJoin = 'Reami:\nUsa /join <realm_id> per entrare\n\n',
        chatNotFound = 'Chat non trovata.',
        aliasSaved = 'Alias salvato.',
        aliasDeleted = 'Alias eliminato.',
        noAliasFound = 'Nessun gruppo trovato con quell\'alias.',
        -- ex inrealm.lua --
        none = 'Nessuno',
        realm = 'Regno ',
        group = 'Gruppo ',
        created = ' creato.',
        chatTypeNotFound = 'Tipo chat non trovato.',
        usersIn = 'Utenti in ',
        alreadyAdmin = ' è già un admin.',
        promoteAdmin = ' è stato promosso ad admin.',
        notAdmin = ' non è un admin.',
        demoteAdmin = ' è stato degradato da admin.',
        noRealms = 'Nessun regno al momento.',
        inThisGroup = ' in questo gruppo',
        groupListStart = 'Gruppi:\n',
        realmListStart = 'Reami:\n',
        logAlreadyYes = 'Gruppo di log già abilitato.',
        logYes = 'Gruppo di log abilitato.',
        logAlreadyNo = 'Gruppo di log già disabilitato.',
        logNo = 'Gruppo di log disabilitato.',
        descriptionSet = 'Descrizione settata per: ',
        errorGroup = 'Errore, gruppo ',
        errorRealm = 'Errore, regno ',
        notFound = ' non trovato',
        chat = 'Chat ',
        removed = ' rimossa',
        groupListCreated = 'Lista gruppi creata.',
        realmListCreated = 'Lista reami creata.',
        -- ex ingroup.lua --
        welcomeNewRealm = 'Benvenuto nel tuo nuovo regno.',
        realmIs = 'Questo è un regno.',
        realmAdded = 'Il regno è stato aggiunto.',
        realmAlreadyAdded = 'Il regno è già stato aggiunto.',
        realmRemoved = 'Il regno è stato rimosso.',
        realmNotAdded = 'Regno non aggiunto.',
        errorAlreadyRealm = 'Errore, è già un regno.',
        errorNotRealm = 'Errore, non è un regno.',
        promotedOwner = 'Sei stato promosso a proprietario.',
        groupIs = 'Questo è un gruppo.',
        groupAlreadyAdded = 'Il gruppo è già stato aggiunto.',
        groupAddedOwner = 'Il gruppo è stato aggiunto e il creatore promosso a proprietario.',
        groupRemoved = 'Il gruppo è stato rimosso.',
        groupNotAdded = 'Gruppo non aggiunto.',
        errorAlreadyGroup = 'Errore, è già un gruppo.',
        errorNotGroup = 'Errore, non è un gruppo.',
        noAutoDemote = 'Non puoi degradarti da solo.',
        -- ex supergroup.lua --
        makeBotAdmin = 'Promuovimi prima amministratrice!',
        groupIs = 'Questo è un gruppo.',
        supergroupAlreadyAdded = 'Il supergruppo è già stato aggiunto.',
        errorAlreadySupergroup = 'Errore, è già un supergruppo.',
        supergroupAdded = 'Il supergruppo è stato aggiunto.',
        supergroupRemoved = 'Il supergruppo è stato rimosso.',
        supergroupNotAdded = 'Supergruppo non aggiunto.',
        membersOf = 'Membri di ',
        membersKickedFrom = 'Membri rimossi da ',
        cantKickOtherAdmin = 'Non puoi rimuovere altri amministratori.',
        promoteSupergroupMod = ' è stato promosso ad amministratore (telegram).',
        demoteSupergroupMod = ' è stato degradato da amministratore (telegram).',
        alreadySupergroupMod = ' è già un amministratore (telegram).',
        notSupergroupMod = ' non è un amministratore (telegram).',
        cantDemoteOtherAdmin = 'Non puoi degradare altri amministratori.',
        leftKickme = 'Uscito tramite /kickme.',
        setOwner = ' ora è l\'owner.',
        inThisSupergroup = ' in questo supergruppo.',
        supergroupUsernameChanged = 'Username supergruppo cambiato.',
        errorChangeUsername = 'Errore nell\'impostare l\'username.\nPotrebbe già essere in uso.\n\nPuoi usare lettere numeri e l\'underscore.\nLunghezza minima 5 caratteri.',
        usernameCleaned = 'Username gruppo pulito.',
        errorCleanedUsername = 'Errore nel tentativo di pulire l\'username.',

        -- info.lua --
        infoWord = 'INFO',
        youAre = '\nTu sei',
        name = '\nNome: ',
        surname = '\nCognome: ',
        username = '\nUsername: ',
        phone = '\nTelefono: ',
        rank = '\nRango: ',
        date = '\nData: ',
        totalMessages = '\nMessaggi totali: ',
        otherInfo = '\nAltre informazioni: ',
        noOtherInfo = 'Nessuna.',
        peer_id = '\nPeer_id: ',
        long_id = '\nId: ',
        chatType = '\nTipo chat: ',
        youAreWriting = '\n\nStai scrivendo a',
        groupName = '\nNome gruppo: ',
        supergroupName = '\nNome supergruppo: ',
        channelName = '\nNome canale: ',
        userWord = 'UTENTE',
        botWord = 'BOT',
        groupWord = 'GRUPPO',
        supergroupWord = 'SUPERGRUPPO',
        channelWord = 'CANALE',
        noObject = 'Nessun oggetto trovato.',
        users = '\nUtenti: ',
        admins = '\nAdmins: ',
        kickedUsers = '\nUtenti rimossi: ',
        userInfo = 'Info utente:',
        peerTypeUnknown = 'Tipo sconosciuto.',
        ishereYes = 'Si.',
        ishereNo = 'No.',
        noLinkAvailable = 'Nessun link disponibile.',

        -- lua_exec.lua --
        doneNoOutput = 'Fatto, nessun output.',

        -- likecounter.lua --
        forwardingLike = 'L\'inoltro dei messaggi per i like non è consentito.',
        likesdbCreated = 'Database likecounter creato.',
        likesLeaderboard = 'Classifica like\n',

        -- me.lua --
        meString = 'Hai mandato W (X%) messaggi e questa chat ne ha Z.',

        -- onservice.lua --
        notMyGroup = 'Questo non è un mio gruppo, addio.',

        -- plugins.lua --
        enabled = ' abilitato.',
        disabled = ' disabilitato.',
        alreadyEnabled = ' già abilitato.',
        alreadyDisabled = ' già disabilitato.',
        notExists = ' non esiste o è disabilitato.',
        systemPlugin = '⛔️ Non è possibile disabilitare questo plugin in quanto è necessario per il corretto funzionamento del sistema.',
        disabledOnChat = ' disabilitato su questa chat.',
        noDisabledPlugin = '❔ Nessun plugin disabilitato su questa chat.',
        pluginNotDisabled = '✔️ Questo plugin non è disabilitato su questa chat.',
        pluginEnabledAgain = ' nuovamente abilitato.',
        pluginsReloaded = '💊 Plugins ricaricati.',

        -- pokedex.lua --
        noPoke = 'Nessun pokémon trovato.',
        pokeName = 'Nome: ',
        pokeWeight = 'Peso: ',
        pokeHeight = 'Altezza: ',

        -- set.lua --
        saved = ' salvato.',
        gSaved = ' variabile globale salvata.',
        mediaSaved = 'Media salvato.',

        -- stats.lua --
        usersInChat = 'Utenti in questa chat\n',
        totalChatMessages = 'Messaggi totali della chat: ',
        groups = '\nGruppi: ',
        statsCleaned = 'Statistiche azzerate.',

        -- strings.lua --
        langUpdate = 'ℹ️ Stringhe aggiornate.',
        langSet = 'ℹ️ Lingua impostata.',

        -- tgcli_to_api_migration.lua --
        migrationCompleted = 'Migrazione completata.',
        migrationAlreadyExecuted = 'Migrazione del gruppo già effettuata.',
        unknownGroupType = 'Errore, tipo di gruppo sconosciuto, ID: ',
        noUserDataAvailable = 'Nessun dato dell\'utente disponibile.',
        noGroupDataAvailable = 'Nessun dato del gruppo disponibile.',

        -- unset.lua --
        deleted = ' eliminato.',
        gDeleted = ' variabile globale eliminata.',

        -- warn.lua --
        errorWarnRange = 'Errore, il range è [0-10].',
        warnSet = 'Il warn è stato impostato a ',
        neverWarn = 'Gli avvertimenti non funzioneranno più.',
        noWarnSet = 'Il warn non è ancora stato impostato.',
        cantWarnHigher = 'Non puoi avvertire un mod/owner/admin/sudo!',
        warned = 'Sei stato avvertito X volte, datti una regolata!',
        unwarned = 'Ti è stato tolto un avvertimento, continua così!',
        alreadyZeroWarnings = 'Sei già a zero avvertimenti.',
        zeroWarnings = 'I tuoi avvertimenti sono stati azzerati.',
        yourWarnings = 'Sei a quota X avvertimenti su un massimo di Y.',

        -- whitelist.lua --
        userBot = 'Utente/Bot ',
        whitelistRemoved = ' rimosso dalla whitelist.',
        whitelistAdded = ' aggiunto alla whitelist.',
        whitelistCleaned = 'Whitelist svuotata.',
        whitelistStart = 'Whitelist:\n',

        -- kick_errors
        kick_errors =
        {
            [1] = 'Non sono admin, non posso kickare utenti',
            [2] = 'Non posso kickare o bannare un admin',
            [3] = 'Non c\'è bisogno di unbannare in un gruppo normale',
            [4] = 'Questo utente non fa parte del gruppo',
        },

        ------------
        -- Usages --
        ------------
        administrator =
        {
            '🅿️ ADMINISTRATOR',
            'Plugin per amministratori di Sasha.',
            'ADMIN',
            '(#pm|sasha messaggia) <user_id> <msg>: Sasha invia <msg> a <user_id>.',
            '(#block|sasha blocca) <id>|<username>|<reply>|from: Sasha blocca l\'utente specificato.',
            '(#unblock|sasha sblocca) <id>|<username>|<reply>|from: Sasha sblocca l\'utente specificato.',
            '#checkspeed: Sasha calcola la velocità con cui processa i messaggi.',
            '#vardump [<reply>]: Sasha esegue il vardump del messaggio specificato.',
            '#commandsstats: Sasha manda gli stats di tutti i comandi.',
            '#ping: Sasha risponde con "Pong".',
            '#laststart: Sasha manda la data dell\'avvio.',
            'SUDO',
            '#botstop: Sasha si stoppa.',
            '#botrestart: Sasha si riavvia.',
            '#redissave: Sasha salva il database redis.',
            '(#sync_gbans|sasha sincronizza superban): Sasha sincronizza la lista dei superban con quella offerta da TeleSeed.',
            '(#backup|sasha esegui backup): Sasha esegue un backup di se stessa e invia il log al richiedente.',
            '(#uploadbackup|sasha invia backup): Sasha invia il suo ultimo backup.',
            '(#rebootcli|sasha riavvia cli): Sasha riavvia la sua versione cli.',
            '#pwr: Sasha usa le API di PWRTelegram.',
            '#api: Sasha usa le API di Telegram.',
        },

        banhammer =
        {
            '🅿️ BANHAMMER',
            'Plugin per la gestione dei kick e dei ban.',
            'USER',
            '(#kickme|sasha (uccidimi|esplodimi|sparami|decompilami|bannami)): Sasha rimuove l\'utente.',
            'MOD',
            '(#getuserwarns|[sasha] ottieni avvertimenti) <id>|<username>|<reply>|from: Sasha manda il numero di avvertimenti ricevuti dall\'utente.',
            '(#warn|[sasha] avverti) <id>|<username>|<reply>|from: Sasha avverte l\'utente.',
            '#unwarn <id>|<username>|<reply>|from: Sasha diminuisce di uno gli avvertimenti dell\'utente.',
            '(#unwarnall|[sasha] azzera avvertimenti) <id>|<username>|<reply>|from: Sasha azzera gli avvertimenti dell\'utente.',
            '(#kick|spara|[sasha] uccidi) <id>|<username>|<reply>|from: Sasha rimuove l\'utente specificato.',
            '(#ban|esplodi|kaboom|[sasha] banna|[sasha] decompila) <id>|<username>|<reply>|from: Sasha banna l\'utente specificato e lo rimuove, se tenta di rientrare viene nuovamente rimosso.',
            '(#unban|[sasha] sbanna|[sasha] [ri]compila) <id>|<username>|<reply>|from: Sasha sbanna l\'utente specificato.',
            '(#banlist|[sasha] lista ban): Sasha mostra la lista di utenti bannati dal gruppo.',
            'OWNER',
            '#kickinactive [<msgs>]: Sasha rimuove gli utenti inattivi.',
            'ADMIN',
            '(#banlist|[sasha] lista ban) <group_id>: Sasha mostra la lista di utenti bannati da <group_id>.',
            '(#gban|[sasha] superbanna) <id>|<username>|<reply>|from: Sasha superbanna l\'utente specificato e lo rimuove, se tenta di rientrare viene nuovamente rimosso.',
            '(#ungban|[sasha] supersbanna) <id>|<username>|<reply>|from: Sasha supersbanna l\'utente specificato.',
            '(#gbanlist|[sasha] lista superban): Sasha mostra la lista di utenti super bannati.',
        },

        bot =
        {
            '🅿️ BOT',
            'Plugin per attivare e disattivare Sasha sul gruppo.',
            'OWNER',
            '#bot|sasha on|off: Sasha si attiva|disattiva.',
            'ADMIN',
            '#bot|sasha <group_id> on|off: Sasha si attiva|disattiva nel gruppo specificato.',
        },

        broadcast =
        {
            '🅿️ BROADCAST',
            'Plugin per mandare messaggi broadcast.',
            'ADMIN',
            '#br <group_id> <text>: Sasha invia <text> a <group_id>.',
            'SUDO',
            '#broadcast <text>: Sasha invia <text> a tutti i gruppi.',
        },

        database =
        {
            '🅿️ DATABASE',
            'Plugin per il salvataggio delle informazioni di utenti e gruppi.',
            'SUDO',
            '#createdatabase: Sasha crea il database.',
            '(#dodatabase|sasha esegui database): Sasha salva i dati di tutti gli utenti del gruppo e i dati del gruppo.',
            '(#dbsearch|[sasha] cerca db) <id>|<username>|<reply>|from: Sasha cerca l\'utente specificato nel database.',
            '(#dbdelete|[sasha] elimina db) <id>: Sasha elimina <id> dal database.',
            '#addrecord user <id>\n<print_name>\n<old_print_names>\n<username>\n<old_usernames>\n<long_id>\n<groups_ids_separated_by_space>: Sasha aggiunge manualmente al database l\'utente specificato.',
            '#addrecord group <id>\n<print_name>\n<old_print_names>\n<lang>: Sasha aggiunge manualmente al database il gruppo specificato.',
            '#addrecord supergroup <id>\n<print_name>\n<old_print_names>\n<lang>\n[<username>\n<old_usernames>]: Sasha aggiunge manualmente al database il supergruppo specificato.',
            '#addrecord channel <id>\n<print_name>\n<old_print_names>\n<lang>\n[<username>\n<old_usernames>]: Sasha aggiunge manualmente al database il canale specificato.',
            '#uploaddb: Sasha manda il database.',
            '#replacedb <reply>: Sasha sostituisce il database.',
        },

        dogify =
        {
            '🅿️ DOGIFY',
            'Plugin per la creazione di immagini col doge.',
            'USER',
            '(#dogify|[sasha] doge) <your/words/with/slashes>: Sasha crea un\'immagine col doge e le parole specificate.',
        },

        fakecommand =
        {
            '🅿️ FAKECOMMAND',
            'Plugin per testare i comandi.',
            'MOD',
            '(#user|#mod|#owner|#admin) <command>: Sasha esegue <command> come se fosse stato inviato da un utente con il rango specificato.',
        },

        feedback =
        {
            '🅿️ FEEDBACK',
            'Plugin per mandare feedback.',
            'USER',
            '#feedback <text>: Sasha invia <text> come feedback.',
        },

        filemanager =
        {
            '🅿️ FILEMANAGER',
            'Plugin per la gestione del server di Sasha.',
            'SUDO',
            '#folder: Sasha manda la directory attuale.',
            '#cd [<directory>]: Sasha entra in <directory>, se non è specificata torna alla cartella base.',
            '#ls: Sasha manda la lista di file e cartelle della directory corrente.',
            '#mkdir <directory>: Sasha crea <directory>.',
            '#rmdir <directory>: Sasha elimina <directory>.',
            '#rm <file>: Sasha elimina <file>.',
            '#touch <file>: Sasha crea <file>.',
            '#cat <file>: Sasha manda il contenuto di <file>.',
            '#tofile <file> <text>: Sasha crea <file> con <text> come contenuto.',
            '#shell <command>: Sasha esegue <command>.',
            '#cp <file> <directory>: Sasha copia <file> in <directory>.',
            '#mv <file> <directory>: Sasha sposta <file> in <directory>.',
            '#upload <file>: Sasha manda <file> nella chat.',
            '#download <reply>: Sasha scarica il file contenuto in <reply>.',
        },

        flame =
        {
            '🅿️ FLAME',
            'Plugin per flammare gli utenti.',
            'MOD',
            '(#startflame|[sasha] flamma) <id>|<username>|<reply>|from: Sasha flamma l\'utente specificato.',
            '(#stopflame|[sasha] stop flame): Sasha smette di flammare.',
            '(#flameinfo|[sasha] info flame): Sasha manda le info su chi sta flammando.',
        },

        get =
        {
            '🅿️ GET',
            'Plugin per ottenere le cose salvate con SET.',
            'USER',
            '(#getlist|#get|sasha lista): Sasha mostra una lista delle variabili settate.',
            '(#getgloballist|#getglobal|sasha lista globali): Sasha mostra una lista delle variabili globali settate.',
            'OWNER',
            '#enableglobal: Sasha abilita i get globali sulla chat.',
            '#disableglobal: Sasha disabilita i get globali sulla chat.',
            '#exportgroupsets: Sasha esporta i set della chat.',
            'ADMIN',
            '#exportglobalsets: Sasha esporta i get globali.',
        },

        goodbyewelcome =
        {
            '🅿️ GOODBYEWELCOME',
            'Plugin per il benvenuto e l\'addio dei membri.',
            'MOD',
            'Possono essere usati dei marcatori che verranno sostituiti quando sarà inviato il benvenuto/l\'addio: $chatid, $chatname, $chatusername, $rules, $userid, $firstname, $lastname, $printname, $username',
            '#getwelcome: Sasha manda il benvenuto.',
            '#getgoodbye: Sasha manda l\'addio.',
            '#previewwelcome: Sasha manda l\'esempio di benvenuto.',
            '#previewgoodbye: Sasha manda l\'esempio di addio.',
            '#setwelcome <text>: Sasha imposta <text> come benvenuto.',
            '#setgoodbye <text>: Sasha imposta <text> come addio.',
            '#unsetwelcome: Sasha rimuove il benvenuto.',
            '#unsetgoodbye: Sasha rimuove l\'addio.',
            '#setmemberswelcome <value>: Sasha dopo <value> membri manderà il benvenuto con le regole, se zero il benvenuto non verrà più mandato.',
            '#getmemberswelcome: Sasha manda il numero di membri entrati dopo i quali invia il benvenuto.',
        },

        group_management =
        {
            '🅿️ GROUP_MANAGEMENT',
            'Plugin per la gestione dei gruppi.',
            -- COMMON
            'USER',
            '#getwarn: Sasha manda il numero di avvertimenti massimi.',
            '(#rules|sasha regole): Sasha mostra le regole del gruppo.',
            '(#modlist|[sasha] lista mod): Sasha mostra la lista dei moderatori.',
            '#owner: Sasha mostra l\'id del proprietario del gruppo.',
            '#admins [<reply>|<text>]: Sasha contatta gli admin',
            'MOD',
            '#type: Sasha mostra il tipo del gruppo.',
            '#updategroupinfo: Sasha aggiorna nome e moderatori del gruppo.',
            '(#setrules|sasha imposta regole) <text>: Sasha imposta <text> come regole.',
            '#setwarn <value>: Sasha imposta gli avvertimenti massimi a <value>, se zero gli avvertimenti non funzioneranno più.',
            '#settings: Sasha mostra le impostazioni del gruppo.',
            '#muteuser|voce <id>|<username>|<reply>|from: Sasha imposta|toglie il muto sull\'utente.',
            '(#muteslist|lista muti): Sasha manda la lista delle variabili mute della chat.',
            '(#mutelist|lista utenti muti): Sasha manda la lista degli utenti muti della chat.',
            '(#link|sasha link): Sasha mostra il link del gruppo.',
            '#setflood <value>: Sasha imposta il flood massimo del gruppo a <value>.',
            '(#lock|[sasha] blocca) arabic|bot|flood|leave|link|member|rtl|spam|strict: Sasha blocca l\'opzione specificata.',
            '(#unlock|[sasha] sblocca) arabic|bot|flood|leave|link|member|rtl|spam|strict: Sasha sblocca l\'opzione specificata.',
            'OWNER',
            '#log: Sasha manda un file contenente il log del gruppo/regno.',
            '(#setlink|sasha imposta link) <link>: Sasha imposta <link> come link d\'invito.',
            '(#unsetlink|sasha elimina link): Sasha elimina il link salvato.',
            '(#getadmins|[sasha] lista admin): Sasha manda la lista degli amministratori.',
            '(#promote|[sasha] promuovi) <id>|<username>|<reply>|from: Sasha promuove a moderatore l\'utente specificato.',
            '(#demote|[sasha] degrada) <id>|<username>|<reply>|from: Sasha degrada l\'utente specificato.',
            '#mute|silenzia all|audio|contact|document|gif|location|photo|sticker|text|tgservice|video|voice: Sasha imposta il muto sulla variabile specificata.',
            '#unmute|ripristina all|audio|contact|document|gif|location|photo|sticker|text|tgservice|video|voice: Sasha rimuove il muto sulla variabile specificata.',
            '#setowner <id>|<username>|<reply>|from: Sasha imposta l\'utente specificato come proprietario.',
            '#clean modlist|rules: Sasha pulisce il parametro specificato.',
            'ADMIN',
            '#add: Sasha aggiunge il gruppo in cui ci si trova.',
            '#rem: Sasha rimuove il gruppo in cui ci si trova.',
            'ex INGROUP.LUA',
            '#add realm: Sasha aggiunge il regno.',
            '#rem realm: Sasha rimuove il regno.',
            'ex INPM.LUA',
            '#allchats: Sasha mostra l\'elenco delle chat.',
            '#allchatlist: Sasha manda un file con l\'elenco delle chat.',
            'REGNO',
            '#setgpowner <group_id> <user_id>: Sasha imposta <user_id> come proprietario di <group_id>.',
            '(#setrules|sasha imposta regole) <group_id> <text>: Sasha cambia le regole di <group_id> in <text>.',
            '(#lock|[sasha] blocca) <group_id> arabic|bot|flood|leave|link|member|rtl|spam|strict: Sasha blocca l\'impostazione specificata di <group_id>.',
            '(#unlock|[sasha] sblocca) <group_id> arabic|bot|flood|leave|link|member|rtl|spam|strict: Sasha sblocca l\'impostazione specificata di <group_id>.',
            '#settings <group_id>: Sasha manda le impostazioni di <group_id>.',
            '#supersettings <supergroup_id>: Sasha manda le impostazioni di <supergroup_id>.',
            '#rem <group_id>: Sasha rimuove il gruppo.',
            '#list admins|groups|realms: Sasha mostra una lista della variabile specificata.',
            'SUDO',
            '#addadmin <user_id>|<username>: Sasha promuove l\'utente specificato ad amminstratore.',
            '#removeadmin <user_id>|<username>: Sasha degrada l\'utente specificato.',
        },

        help =
        {
            '🅿️ HELP',
            'Plugin di aiuto, USATELO!',
            'USER',
            '(#sudolist|sasha lista sudo): Sasha manda la lista dei sudo.',
            '(#help|sasha aiuto): Sasha mostra una lista dei plugin disponibili.',
            '(#help|sasha aiuto) <plugin_name>|<plugin_number>: Sasha mostra l\'aiuto per il plugin specificato.',
            '(#helpall|sasha aiuto tutto): Sasha mostra tutti i comandi di tutti i plugin.',
            '(#syntax|sasha sintassi) <filter>: Sasha mostra la sintassi dei comandi che corrispondono a <filter>.',
            '(#syntaxall|sasha sintassi tutto): Sasha mostra la sintassi di tutti i comandi di tutti i plugin.',
        },

        info =
        {
            '🅿️ INFO',
            'Plugin per ottenere informazioni.',
            'USER',
            '#getrank|rango [<id>|<username>|<reply>]: Sasha manda il rank dell\'utente.',
            '#whoami: Sasha manda le informazioni dell\'utente.',
            '(#info|[sasha] info): Sasha manda le info dell\'utente e della chat o di se stessa',
            '#ishere <id>|<username>|<reply>|from: Sasha dice se l\'utente specificato è presente nel gruppo.',
            'MOD',
            '(#info|[sasha] info) <id>|<username>|<reply>|from: Sasha manda le info del parametro specificato.',
            'ADMIN',
            '(#grouplink|[sasha] link gruppo) <group_id>: Sasha manda il link del gruppo specificato.',
        },

        interact =
        {
            '🅿️ INTERACT',
            'Plugin per l\'interazione con gli utenti.',
            'MOD',
            '(#echo|sasha ripeti) [<reply>]<text>: Sasha ripete <text>, se in risposta ad un messaggio sasha risponde a quel messaggio.',
        },

        likecounter =
        {
            '🅿️ LIKECOUNTER',
            'Plugin per il conteggio dei likes.',
            'USER',
            '#like|#1up <id>|<username>|<reply>|from: Sasha aggiunge un like all\'utente specificato.',
            '#dislike|#1down <id>|<username>|<reply>|from: Sasha toglie un like all\'utente specificato.',
            '#likes: Sasha manda la classifica dei likes.',
            'SUDO',
            '#createlikesdb:  Sasha crea il database di likecounter.',
            '#addlikes <id> <value>: Sasha aggiunge <value> likes all\'utente specificato.',
            '#remlikes <id> <value>: Sasha toglie <value> likes all\'utente specificato.',
        },

        lua_exec =
        {
            '🅿️ LUA_EXEC',
            'Plugin per l\'esecuzione di codice LUA.',
            'SUDO',
            '#lua <command>: Sasha esegue <command>.',
        },

        me =
        {
            '🅿️ ME',
            'Plugin per sapere i messaggi mandati.',
            'USER',
            '#me: Sasha dice quanti messaggi hai mandato.',
        },

        onservice =
        {
            '🅿️ ONSERVICE',
            'Plugin per far abbandonare un gruppo a Sasha.',
            'ADMIN',
            '(#leave|sasha abbandona) [<group_id>]: Sasha lascia il gruppo.',
        },

        plugins =
        {
            '🅿️ PLUGINS',
            'Plugin per attivare e disattivare plugin.',
            'OWNER',
            '(#plugins|[sasha] lista plugins): Sasha mostra una lista di tutti i plugins.',
            '(#disabledlist|([sasha] lista disabilitati|disattivati)): Sasha mostra una lista dei plugins disabilitati su questa chat.',
            '(#enable|[sasha] abilita|[sasha] attiva) <plugin> chat: Sasha riabilita <plugin> su questa chat.',
            '(#disable|[sasha] disabilita|[sasha] disattiva) <plugin> chat: Sasha disabilita <plugin> su questa chat.',
            'SUDO',
            '(#enable|[sasha] abilita|[sasha] attiva) <plugin> [chat]: Sasha abilita <plugin>, se specificato solo su questa chat.',
            '(#disable|[sasha] disabilita|[sasha] disattiva) <plugin> [chat]: Sasha disabilita <plugin>, se specificato solo su questa chat.',
            '(#reload|[sasha] ricarica): Sasha ricarica tutti i plugins.',
        },

        pokedex =
        {
            '🅿️ POKEDEX',
            'Plugin per ottenere informazioni su un pokémon.',
            'USER',
            '#pokedex|#pokemon <name>|<id>: Sasha cerca il pokémon specificato e ne invia le informazioni.',
        },

        qr =
        {
            '🅿️ QR',
            'Plugin per creare QR Code.',
            'USER',
            '(#qr|sasha qr) ["<background_color>" "<data_color>"] <text>: Sasha crea il QR Code di <text>, se specificato colora il QR Code.',
            'I colori possono essere specificati come segue:',
            'Testo => red|green|blue|purple|black|white|gray.',
            'Notazione Esadecimale => ("a56729" è marrone).',
            'Notazione Decimale => ("255-192-203" è rosa).',
        },

        reactions =
        {
            '🅿️ REACTIONS',
            'Plugin per far reagire Sasha.',
            'MOD',
            '#typing: Sasha finge di scrivere.',
            '#upload_photo: Sasha finge di inviare una foto.',
            '#record_video: Sasha finge di registrare un video.',
            '#upload_video: Sasha finge di inviare un video.',
            '#record_audio: Sasha finge di registrare un audio.',
            '#upload_audio: Sasha finge di inviare un audio.',
            '#upload_document: Sasha finge di inviare un documento.',
            '#find_location: Sasha finge di inviare una posizione.',
        },

        set =
        {
            '🅿️ SET',
            'Plugin per salvare cose.',
            'MOD',
            '(#set|[sasha] setta) <var_name> <text>: Sasha salva <text> come risposta a <var_name>.',
            '(#setmedia|[sasha] setta media) <var_name> <reply>: Sasha salva il media (foto, video, audio, nota vocale, documento, sticker) in <reply> come risposta a <var_name>.',
            'ADMIN',
            '#setglobal <var_name> <text>: Sasha salva globalmente <text> come risposta a <var_name>.',
        },

        shout =
        {
            '🅿️ SHOUT',
            'Plugin per urlare delle parole.',
            'USER',
            '(#shout|[sasha] grida|[sasha] urla) <text>: Sasha "urla" <text>.',
        },

        stats =
        {
            '🅿️ STATS',
            'Plugin per ottenere statistiche sui gruppi e su Sasha.',
            'USER',
            '[#]aisashabot: Sasha invia la propria descrizione.',
            'MOD',
            '(#stats|#messages): Sasha invia le statistiche della chat.',
            '(#cleanstats|#cleanmessages): Sasha pulisce le statistiche.',
            '(#statslist|#messageslist): Sasha invia un file con le statistiche della chat.',
            'ADMIN',
            '(#stats|#messages) group <group_id>: Sasha invia le statistiche relative al gruppo specificato.',
            '(#cleanstats|#cleanmessages) group <group_id>: Sasha pulisce le statistiche relative al gruppo specificato.',
            '(#statslist|#messageslist) group <group_id>: Sasha invia un file con le statistiche relative al gruppo specificato.',
        },

        strings =
        {
            '🅿️ STRINGS',
            'Plugin per la gestione delle lingue di Sasha.',
            'USER',
            '(#setlang|lingua) (it|en): Sasha imposta la lingua in cui deve parlare (funziona solo in privato con l\'utente).',
            'OWNER',
            '(#setlang|lingua) (it|en): Sasha imposta la lingua in cui deve parlare in questo gruppo.',
            'SUDO',
            '(#reloadstrings|[sasha] aggiorna stringhe): Sasha aggiorna le stringhe di testo.',
        },

        tex =
        {
            '🅿️ TEX',
            'Plugin per generare equazioni.',
            'USER',
            '(#tex|[sasha] equazione) <equation>: Sasha converte <equation> in immagine.',
        },

        tgcli_to_api_migration =
        {
            '🅿️ TGCLI_TO_API_MIGRATION',
            'Plugin per la migrazione da tgcli.',
            'OWNER',
            '#migrate: Sasha migra le impostazioni del gruppo, i ban, le variabili settate e i likes.',
            'SUDO',
            '#sudomigrate: Sasha migra i database e i set globali.',
        },

        unset =
        {
            '🅿️ UNSET',
            'Plugin per eliminare cose salvate con SET.',
            'MOD',
            '(#unset|[sasha] unsetta) <var_name>: Sasha elimina <var_name>.',
            'ADMIN',
            '#unsetglobal <var_name>: Sasha elimina globalmente <var_name>.',
        },

        urbandictionary =
        {
            '🅿️ URBANDICTIONARY',
            'Plugin per interagire con l\'Urban Dictionary.',
            'USER',
            '(#urbandictionary|#urban|#ud|[sasha] urban|[sasha] ud) <text>: Sasha mostra la definizione di <text> dall\'Urban Dictionary.',
        },

        webshot =
        {
            '🅿️ WEBSHOT',
            'Plugin per fare screenshots di siti.',
            'MOD',
            '(#webshot|[sasha] webshotta) <url> [<size>]: Sasha esegue uno screenshot di <url> e lo invia, se <size> è specificata di quella dimensione.',
            'La dimensione può essere:',
            'T: (120 x 90px)',
            'S: (200 x 150px)',
            'E: (320 x 240px)',
            'N: (400 x 300px)',
            'M: (640 x 480px)',
            'L: (800 x 600px)',
            'X: (1024 x 768px)',
            'Nmob: (480 x 800px)',
            'ADMIN',
            'F: Pagina intera (può essere un processo molto lungo)',
            'Fmob: Pagina intera (può essere un processo lungo)',
        },

        whitelist =
        {
            '🅿️ WHITELIST',
            'Plugin per la gestione della whitelist.',
            'ADMIN',
            '#whitelist [<id>|<username>|<reply>]: Sasha aggiunge|rimuove l\'utente specificato alla|dalla whitelist, se nulla è specificato Sasha manda la whitelist.',
            '#clean whitelist: Sasha pulisce la whitelist.',
        },
    },
    -- ####
    en =
    {
        -- global --
        require_sudo = '🚫 This plugin requires sudo privileges.',
        require_admin = '🚫 This plugin requires admin privileges or higher.',
        require_owner = '🚫 This plugin requires owner privileges or higher.',
        require_mod = '🚫 This plugin requires mod privileges or higher.',
        require_rank = '🚫 You can\'t do this to someone who\'s higher than you or at your same rank!',
        errorTryAgain = 'Error, try again.',
        opsError = 'Ops, error.',
        useYourGroups = 'Use it in your groups!',
        user = 'User ',
        kicked = ' kicked.',
        banned = ' banned.',
        unbanned = ' unbanned.',
        gbanned = ' globally banned.',
        ungbanned = ' globally unbanned.',
        cantDoThisToChat = 'You can\'t use this command on a message forwarded from a channel.',
        errorNoForward = 'It\'s not a forwarded message.',

        -- seedbot.lua --
        sender = 'Sender: ',
        receiver = 'Receiver: ',
        msgText = 'Message: ',
        groupToSupergroup = 'Service notification: group migration executed with success.',
        loopWithoutMessage = '*A loop without message.*',
        botStarted = '*Bot started!*\n_X_\nY plugins loaded.',

        -- utils.lua --
        errorFileDownload = 'Error downloading the picture.',
        banListStart = 'Banlist:\n\n',
        gbanListStart = 'GBanlist:\n\n',
        mutedUsersStart = 'Muted users of: ',
        mutedTypesStart = 'Mutes of: ',
        mute = 'Mute ',
        mutesSet = 'Mutes set.',
        alreadyEnabled = ' already enabled.',
        enabled = ' enabled.',
        alreadyDisabled = ' already disabled.',
        disabled = ' disabled',
        noAutoKick = 'You can\'t kick yourself.',
        noAutoBan = 'You can\'t ban yourself.',

        -- administrator.lua --
        sendNewPic = 'Send me the new picture.',
        botPicChanged = 'Picture changed!',
        logSet = 'Log added.',
        logUnset = 'Log removed.',
        markRead = 'Mark read',
        pmSent = 'Message sent',
        cantBlockAdmin = 'You can\'t block admins.',
        userBlocked = 'User blocked.',
        userUnblocked = 'User unblocked.',
        contactListSent = 'I\'ve sent you the contactlist in the requested format.',
        removedFromContacts = ' removed from contacts.',
        addedToContacts = ' added to contacts.',
        contactMissing = 'I haven\'t got your phone number!',
        chatListSent = 'I\'ve sent you the dialoglist in the requested format.',
        gbansSync = 'GBanlist sync completed.',
        longidUpdate = 'Update long_ID.',
        alreadyLog = 'Already a log group.',
        notLog = 'Not a log group.',
        backupDone = 'Backup finished, I\'m sending you the log.',
        backupSent = 'I\'m sending you the backup.',
        backupMissing = 'Backup missing.',
        autoSendBackupDb = '*I\'m sending you the automatic backup.*',
        botStats = 'Bot\'s stats: ',
        botRestarted = 'Bot reloaded.',
        botStopped = 'Bot stopped.',
        redisDbSaved = 'Redis db saved.',
        cliReboot = 'AISasha Killed.',
        ok = 'Ok.',

        -- anti_spam.lua --
        blockedForSpam = ' blocked (SPAM).',
        floodNotAdmitted = 'Flooding is not admitted.\n',
        statusRemoved = 'User kicked.',
        gbannedFrom = ' globally banned from ',

        -- banhammer.lua --
        noUsernameFound = 'Can\'t find a user with that username.',
        massacre = 'Massacre => X',
        cantKickWhitelisted = 'Can\'t kick a whitelisted user.',

        -- bot.lua --
        startMessage = 'Hi, I\'m the API version of @AISasha, as for my user version only my creator can add me to a group, for anything you need use /help.',
        botOn = 'I\'m back. 😏',
        botOff = 'Nothing to do here. 🚀',

        -- database.lua --
        dbCreated = 'Database created.',
        dataLeaked = 'Data leaked.',
        userManuallyAdded = 'User manually added to the database.',
        groupManuallyAdded = 'Group manually added to the database.',
        supergroupManuallyAdded = 'Supergroup manually added to the database.',
        channelManuallyAdded = 'Channel manually added to the database.',
        recordDeleted = 'Record deleted.',
        needJson = 'I need a json file.',
        errorUserOrGroup = 'Just groups or users.',
        userDeleted = 'User deleted from database.',
        groupDeleted = 'Group deleted from database.',
        databaseDownloaded = 'Database downloaded\n',
        databaseSent = 'I\'m sending you the database.',
        databaseMissing = 'Database missing.',
        databaseFuckedUp = '*Error, crash while saving database, restore it as soon as possible.*',

        -- fakecommand.lua --
        fakecommandYouTried = 'You tried asshole, you won\'t execute a command that requires a rank higher than yours.',

        -- feedback.lua --
        feedStart = '@EricSolinas you received a feedback: #newfeedback\n\nSender',
        feedName = '\nName: ',
        feedSurname = '\nSurname: ',
        feedUsername = '\nUsername: @',
        feedSent = 'Feedback sent!',

        -- filemanager.lua --
        backHomeFolder = 'You\'re in the base folder: ',
        youAreHere = 'You are here: ',
        folderCreated = 'Folder \'X\' created.',
        folderDeleted = 'Folder \'X\' deleted.',
        fileCreatedWithContent = ' created with \'X\' as contents.',
        copiedTo = ' copied to ',
        movedTo = ' moved to ',
        sendingYou = 'I\'m sending ',
        useQuoteOnFile = 'Use \'reply\' on the file you want me to download.',
        needMedia = 'I need a file.',
        fileDownloadedTo = 'File downloaded to: ',
        errorDownloading = 'Error during the download.',
        noSuchFile = ' doesn\'t exist.',

        -- flame.lua --
        cantFlameHigher = 'You can\'t flame mod/owner/admin/sudo/!',
        noAutoFlame = 'I can\'t flame myself you jerk!',
        hereIAm = 'Here I am!',
        stopFlame = 'Yeah I\'m done, holy shit.',
        flaming = 'I\'m flaming: ',
        errorParameter = 'Redis variable missing.',

        -- help.lua --
        require_higher = '🚫 This plugin requires higher privileges.\n',
        pluginListStart = 'ℹ️Plugins list: \n\n',
        helpInfo = 'ℹ️Write "!help <plugin_name>|<plugin_number>" for more info on that plugin.\nℹ️Or "!helpall" to have all commands.',
        errorNoPlugin = 'This plugin doesn\'t exist or doesn\'t have a description.',
        helpIntro = 'Every \'#\' can be replaced with \'/\' or \'!\'.\nAll commands are Case Insensitive.\nSquare brackets means that is an optional.\nRound brackets with \'|\' means that\'s a choice".\n\n',
        commandNotFound = 'Sintassi comando non trovata.',

        -- get.lua --
        globalEnable = 'Global variables enabled on this chat.',
        globalDisable = 'Global variables disabled on this chat.',

        -- goodbyewelcome.lua --
        newWelcome = 'New welcome message:\n',
        newGoodbye = 'New goodbye message:\n',
        welcomeRemoved = 'Welcome removed.',
        goodbyeRemoved = 'Goodbye removed.',
        newWelcomeNumber = 'Welcome message will be sent every X members.',
        neverWelcome = 'Welcome message will not be sent anymore.',
        noSetValue = 'No value set.',

        -- group_management.lua --
        -- locks --
        settingAlreadyLocked = 'Setting already locked.',
        settingLocked = 'Setting locked.',
        settingAlreadyUnlocked = 'Setting already unlocked.',
        settingUnlocked = 'Setting unlocked.',
        alreadyMuted = ' already muted.',
        muted = ' muted.',
        alreadyUnmuted = ' already unmuted.',
        unmuted = ' unmuted.',
        arabicLock = '\nLock arabic: ',
        botsLock = '\nLock bots: ',
        floodLock = '\nLock flood: ',
        floodSensibility = '\nFlood sensibility: ',
        leaveLock = '\nLock leave: ',
        linksLock = '\nLock links: ',
        membersLock = '\nLock members: ',
        rtlLock = '\nLock RTL: ',
        spamLock = '\nLock spam: ',
        strictrules = '\nStrict rules: ',
        warnSensibility = '\nMax warns: ',
        noSuchMuteType = 'No mute applicable to the specified variable.',
        -- ex common --
        groupInfoUpdated = 'Group name and mods updated.',
        newDescription = 'New description:\n',
        noDescription = 'No description available.',
        description = 'Chat description: ',
        newRules = 'New rules:\n',
        noRules = 'No rules available.',
        rules = 'Chat rules:\n',
        sendNewGroupPic = 'Send the new group picture.',
        photoSaved = 'Picture saved.',
        groupSettings = 'Group settings: ',
        supergroupSettings = 'Supergroup settings: ',
        noGroups = 'No groups at the moment.',
        errorFloodRange = 'Error, range is [3-200]',
        floodSet = 'Flood set to ',
        noOwnerCallAdmin = 'No owner, contact an admin to set one.',
        ownerIs = 'Group owner is ',
        errorCreateLink = 'Error, can\'t create link.\nI\'m not the owner.',
        errorCreateSuperLink = 'Error, can\'t create link.\nI\'m not the owner.\n\nIf you have the link use /setlink to set it',
        sendMeLink = 'Create a link using /newlink.',
        linkCreated = 'New link created.',
        groupLink = 'Link\n',
        adminListStart = 'Admins:\n',
        alreadyMod = ' is already a mod.',
        promoteMod = ' has been promoted to mod.',
        notMod = ' is not a mod.',
        demoteMod = ' has been demoted from mod.',
        noGroupMods = 'No mod in this group.',
        modListStart = 'Mods of ',
        muteUserAdd = ' added to muted users list.',
        muteUserRemove = ' removed from muted users list.',
        modlistCleaned = 'Mod list cleaned.',
        rulesCleaned = 'Rules cleaned.',
        descriptionCleaned = 'Description cleaned.',
        mutelistCleaned = 'Mute list cleaned.',
        cantContact = 'If (s)he doesn\'t write me first I can\'t contact ',
        -- ex inpm.lua --
        groupsJoin = 'Groups:\nUse /join <group_id> to join\n\n',
        realmsJoin = 'Realm:\nUse /join <realm_id> to join\n\n',
        chatNotFound = 'Chat not found.',
        aliasSaved = 'Alias saved.',
        aliasDeleted = 'Alias deleted.',
        noAliasFound = 'No group with that alias.',
        -- ex inrealm.lua --
        none = 'No one',
        realm = 'Realm ',
        group = 'Groups ',
        created = ' created.',
        chatTypeNotFound = 'Chat type not found.',
        usersIn = 'Users in ',
        alreadyAdmin = ' is already admin.',
        promoteAdmin = ' has been promoted to admin.',
        notAdmin = ' is not admin.',
        demoteAdmin = ' has been demoted from admin.',
        noRealms = 'No realm at the moment.',
        inThisGroup = ' in this group',
        groupListStart = 'Groups:\n',
        realmListStart = 'Realms:\n',
        logAlreadyYes = 'Log group already enabled.',
        logYes = 'Log group enabled.',
        logAlreadyNo = 'Log group already disabled.',
        logNo = 'Log group disabled.',
        descriptionSet = 'Description set for: ',
        errorGroup = 'Error, group ',
        errorRealm = 'Error, realm ',
        notFound = ' not found',
        chat = 'Chat ',
        removed = ' removed',
        groupListCreated = 'Group list created.',
        realmListCreated = 'Realm list created.',
        -- ex ingroup.lua --
        welcomeNewRealm = 'Welcome to your new realm.',
        realmIs = 'This is a realm.',
        realmAdded = 'Realm has been added.',
        realmAlreadyAdded = 'Realm is already added.',
        realmRemoved = 'Realm has been removed.',
        realmNotAdded = 'Realm not added.',
        errorAlreadyRealm = 'Error, already a realm.',
        errorNotRealm = 'Error, not a realm.',
        promotedOwner = 'You\'ve been promoted as owner.',
        groupIs = 'This is a group.',
        groupAlreadyAdded = 'Group is already added.',
        groupAddedOwner = 'Group has been added and the creator has been promoted as owner.',
        groupRemoved = 'Group has been removed.',
        groupNotAdded = 'Group not added.',
        errorAlreadyGroup = 'Error, already a group.',
        errorNotGroup = 'Error, not a group.',
        noAutoDemote = 'You can\'t demote yourself.',
        -- ex supergroup.lua --
        makeBotAdmin = 'Promote me as administrator!',
        groupIs = 'This is a group.',
        supergroupAlreadyAdded = 'Supergroup already added.',
        errorAlreadySupergroup = 'Error, already a supergroup.',
        supergroupAdded = 'Supergroup has been added.',
        supergroupRemoved = 'Supergroup has been removed.',
        supergroupNotAdded = 'Supergroup not added.',
        membersOf = 'Members of ',
        membersKickedFrom = 'Members kicked from ',
        cantKickOtherAdmin = 'You can\'t kick other admins.',
        promoteSupergroupMod = ' has been promoted to administrator (telegram).',
        demoteSupergroupMod = ' has been demoted from administrator (telegram).',
        alreadySupergroupMod = ' is already an administrator (telegram).',
        notSupergroupMod = ' is not an administrator (telegram).',
        cantDemoteOtherAdmin = 'You can\'t demote other admins.',
        leftKickme = 'Left using /kickme.',
        setOwner = ' is the owner.',
        inThisSupergroup = ' in this supergroup.',
        linkSaved = 'New link set.',
        linkDeleted = 'Link deleted.',
        supergroupUsernameChanged = 'Supergroup username changed.',
        errorChangeUsername = 'Error changing username.\nIt could be already in use.\n\nYou can use letters numbers and underscore.\nMinimum length 5 characters.',
        usernameCleaned = 'Supergroup username cleaned.',
        errorCleanedUsername = 'Error while cleaning supergroup username.',

        -- info.lua --
        infoWord = 'INFO',
        youAre = '\nYou are',
        name = '\nName: ',
        surname = '\nSurname: ',
        username = '\nUsername: ',
        phone = '\nPhone: ',
        rank = '\nRank: ',
        date = '\nDate: ',
        totalMessages = '\nTotal messages: ',
        otherInfo = '\nOther info: ',
        noOtherInfo = 'Nothing.',
        peer_id = '\nPeer_id: ',
        long_id = '\nId: ',
        chatType = '\nChat type: ',
        youAreWriting = '\n\nYou are writing to',
        groupName = '\nGroup name: ',
        supergroupName = '\nSupergroup name: ',
        channelName = '\nChannel name: ',
        userWord = 'USER',
        botWord = 'BOT',
        groupWord = 'GROUP',
        supergroupWord = 'SUPERGROUP',
        channelWord = 'CHANNEL',
        noObject = 'No object found.',
        users = '\nUsers: ',
        admins = '\nAdmins: ',
        kickedUsers = '\nKicked users: ',
        userInfo = 'User info:',
        peerTypeUnknown = 'Type unknown.',
        ishereYes = 'Yes.',
        ishereNo = 'No.',
        noLinkAvailable = 'No link available.',

        -- lua_exec.lua --
        doneNoOutput = 'Done, no output.',

        -- likecounter.lua --
        forwardingLike = 'Forwarding for likes is not allowed.',
        likesdbCreated = 'Likecounter database created.',
        likesLeaderboard = 'Likes leaderboard\n',

        -- me.lua --
        meString = 'You have sent W (X%) messages and this chat has Z messages.',

        -- onservice.lua --
        notMyGroup = 'This is not one of my groups, bye.',

        -- plugins.lua --
        enabled = ' enabled.',
        disabled = ' disabled.',
        alreadyEnabled = ' already enabled.',
        alreadyDisabled = ' already disabled.',
        notExists = ' not exists or is disabled.',
        systemPlugin = '⛔️ You can\'t disable this plugin because is a system one.',
        disabledOnChat = ' disabled on chat.',
        noDisabledPlugin = '❔ No plugins disabled on chat.',
        pluginNotDisabled = '✔️ This plugin is not disabled on chat.',
        pluginEnabledAgain = ' enabled on chat again.',
        pluginsReloaded = '💊 Plugins reloaded.',

        -- pokedex.lua --
        noPoke = 'No pokémon found.',
        pokeName = 'Name: ',
        pokeWeight = 'Weight: ',
        pokeHeight = 'Height: ',

        -- set.lua --
        saved = ' saved.',
        gSaved = ' global variable saved.',
        mediaSaved = 'Media saved.',

        -- stats.lua --
        usersInChat = 'Users on chat\n',
        totalChatMessages = 'Total messages of the chat: ',
        groups = '\nGroups: ',
        statsCleaned = 'Stats cleaned.',

        -- strings.lua --
        langUpdate = 'ℹ️ Strings updated.',
        langSet = 'ℹ️ Language set.',

        -- tgcli_to_api_migration.lua --
        migrationCompleted = 'Migration completed.',
        migrationAlreadyExecuted = 'Group migration already executed.',
        unknownGroupType = 'Error, unknown group type, ID: ',
        noUserDataAvailable = 'No available data for the user.',
        noGroupDataAvailable = 'No available data for the group.',

        -- unset.lua --
        deleted = ' deleted.',
        gDeleted = ' global variable deleted.',

        -- warn.lua --
        errorWarnRange = 'Error, range is [0-10].',
        warnSet = 'Warn has been set to ',
        neverWarn = 'Warn will not work anymore.',
        noWarnSet = 'Warn hasn\t been set yet.',
        cantWarnHigher = 'You can\'t warn mod/owner/admin/sudo!',
        warned = 'You\'ve been warned X times, calm down!',
        unwarned = 'One warn has been deleted, keep it up!',
        alreadyZeroWarnings = 'You\'re already at zero warns.',
        zeroWarnings = 'Your warns has been removed.',
        yourWarnings = 'You\'re at X warns on Y.',

        -- whitelist.lua --
        userBot = 'User/Bot ',
        whitelistRemoved = ' removed from whitelist.',
        whitelistAdded = ' added to whitelist.',
        whitelistCleaned = 'Whitelist cleaned.',
        whitelistStart = 'Whitelist:\n',

        -- kick_errors
        kick_errors =
        {
            [1] = 'I\'m not an admin, I can\'t kick people',
            [2] = 'I can\'t kick or ban an admin',
            [3] = 'There is no need to unban in a normal group',
            [4] = 'This user is not a chat member',
        },

        ------------
        -- Usages --
        ------------
        administrator =
        {
            '🅿️ ADMINISTRATOR',
            'Plugin for Sasha\'s administrators.',
            'ADMIN',
            '(#pm|sasha messaggia) <user_id> <msg>: Sasha writes <msg> to <user_id>.',
            '(#block|sasha blocca) <id>|<username>|<reply>|from: Sasha blocks specified user.',
            '(#unblock|sasha sblocca) <id>|<username>|<reply>|from: Sasha unblocks specified user.',
            '#checkspeed: Sasha calculates how much time she needs to process messages.',
            '#vardump [<reply>]: Sasha sends vardump of specified message.',
            '#commandsstats: Sasha sends commands stats.',
            '#ping: Sasha answers with "Pong".',
            '#laststart: Sasha sends last start date.',
            'SUDO',
            '#botstop: Sasha stops.',
            '#botrestart: Sasha restarts.',
            '#redissave: Sasha saves redis db.',
            '(#sync_gbans|sasha sincronizza superban): Sasha syncs gbans list with the one offered by TeleSeed.',
            '(#backup|sasha esegui backup): Sasha makes a backup of herself and sends log to the sender.',
            '(#uploadbackup|sasha invia backup): Sasha sends her last backup.',
            '(#rebootcli|sasha riavvia cli): Sasha reboots her cli version.',
            '#pwr: Sasha uses PWRTelegram API.',
            '#api: Sasha uses Telegram API.',
        },

        banhammer =
        {
            '🅿️ BANHAMMER',
            'Plugin for the management of kick and bans.',
            'USER',
            '(#kickme|sasha (uccidimi|esplodimi|sparami|decompilami|bannami)): Sasha kicks sender.',
            'MOD',
            '(#getuserwarns|[sasha] ottieni avvertimenti) <id>|<username>|<reply>|from: Sasha sends user\'s warns.',
            '(#warn|[sasha] avverti) <id>|<username>|<reply>|from: Sasha warns specified user.',
            '#unwarn <id>|<username>|<reply>|from: Sasha removes one warn from specified user.',
            '(#unwarnall|[sasha] azzera avvertimenti) <id>|<username>|<reply>|from: Sasha removes all warns from specified user.',
            '(#kick|spara|[sasha] uccidi) <id>|<username>|<reply>|from: Sasha kicks specified user.',
            '(#ban|esplodi|kaboom|[sasha] banna|[sasha] decompila) <id>|<username>|<reply>|from: Sasha kicks and bans specified user, if he tries to join again it\'s automatically kicked.',
            '(#unban|[sasha] sbanna|[sasha] [ri]compila) <id>|<username>|<reply>|from: Sasha unbans specified user.',
            '(#banlist|[sasha] lista ban): Sasha sends bans list of the group.',
            'OWNER',
            '#kickinactive [<msgs>]: Sasha kicks inactive users.',
            'ADMIN',
            '(#banlist|[sasha] lista ban) <group_id>: Sasha sends bans list of <group_id>.',
            '(#gban|[sasha] superbanna) <id>|<username>|<reply>|from: Sasha kicks and gbans specified user, if he tries to join again it\'s automatically kicked.',
            '(#ungban|[sasha] supersbanna) <id>|<username>|<reply>|from: Sasha ungbans specified user.',
            '(#gbanlist|[sasha] lista superban): Sasha sends gbans list.',
        },

        bot =
        {
            '🅿️ BOT',
            'Plugin to enable or disable Sasha on the group.',
            'OWNER',
            '#bot|sasha on|off: Sasha goes on|off on the group.',
            'ADMIN',
            '#bot|sasha <group_id> on|off: Sasha goes on|off on the specified group.',
        },

        broadcast =
        {
            '🅿️ BROADCAST',
            'Plugin to send broadcast messages.',
            'ADMIN',
            '#br <group_id> <text>: Sasha sends <text> to <group_id>.',
            'SUDO',
            '#broadcast <text>: Sasha sends <text> to all groups.',
        },

        database =
        {
            '🅿️ DATABASE',
            'Plugin to save all users and groups info.',
            'SUDO',
            '#createdatabase: Sasha creates the database.',
            '(#dodatabase|sasha esegui database): Sasha saves all info of all users of group and group info.',
            '(#dbsearch|[sasha] cerca db) <id>|<username>|<reply>|from: Sasha searches for the specified user in the database.',
            '(#dbdelete|[sasha] elimina db) <id>: Sasha deleted <id> from the database.',
            '#addrecord user <id>\n<print_name>\n<old_print_names>\n<username>\n<old_usernames>\n<long_id>\n<groups_ids_separated_by_space>: Sasha manually adds specified user to the database.',
            '#addrecord group <id>\n<print_name>\n<old_print_names>\n<lang>: Sasha manually adds specified group to the database.',
            '#addrecord supergroup <id>\n<print_name>\n<old_print_names>\n<lang>\n[<username>\n<old_usernames>]: Sasha manually adds specified supergroup to the database.',
            '#addrecord channel <id>\n<print_name>\n<old_print_names>\n<lang>\n[<username>\n<old_usernames>]: Sasha manually adds specified channel to the database.',
            '#uploaddb: Sasha uploads the database.',
            '#replacedb <reply>: Sasha replaces the database.',
        },

        dogify =
        {
            '🅿️ DOGIFY',
            'Plugin to create picture with doge.',
            'USER',
            '(#dogify|[sasha] doge) <your/words/with/slashes>: Sasha creates a pic with doge and specified words.',
        },

        fakecommand =
        {
            '🅿️ FAKECOMMAND',
            'Plugin to test commands.',
            'MOD',
            '(#user|#mod|#owner|#admin) <command>: Sasha executes <command> as it would be sent by a user with the specified rank.',
        },

        feedback =
        {
            '🅿️ FEEDBACK',
            'Plugin for feedbacks.',
            'USER',
            '#feedback <text>: Sasha sends <text> as feedback.',
        },

        filemanager =
        {
            '🅿️ FILEMANAGER',
            'Plugin for the management of Sasha\'s server.',
            'SUDO',
            '#folder: Sasha sends actual directory.',
            '#cd [<directory>]: Sasha enters in <directory>, if it\'s not specified it returns to base folder.',
            '#ls: Sasha sends the list of files and folders of the current directory.',
            '#mkdir <directory>: Sasha creates <directory>.',
            '#rmdir <directory>: Sasha deletes <directory>.',
            '#rm <file>: Sasha deletes <file>.',
            '#touch <file>: Sasha creates <file>.',
            '#cat <file>: Sasha sends <file> content.',
            '#tofile <file> <text>: Sasha creates <file> with <text> as content.',
            '#shell <command>: Sasha executes <command>.',
            '#cp <file> <directory>: Sasha copies <file> in <directory>.',
            '#mv <file> <directory>: Sasha moves <file> in <directory>.',
            '#upload <file>: Sasha uploads <file> on chat.',
            '#download <reply>: Sasha downloads the file in <reply>.',
        },

        flame =
        {
            '🅿️ FLAME',
            'Plugin to start flames.',
            'MOD',
            '(#startflame|[sasha] flamma) <id>|<username>|<reply>|from: Sasha flames specified user.',
            '(#stopflame|[sasha] stop flame): Sasha stops flame.',
            '(#flameinfo|[sasha] info flame): Sasha sends flamed user info.',
        },

        get =
        {
            '🅿️ GET',
            'Plugin to get things saved with SET.',
            'USER',
            '(#getlist|#get|sasha lista): Sasha sends a list of saved variables.',
            '(#getgloballist|#getglobal|sasha lista globali): Sasha sends a list of globally saved variables.',
            'OWNER',
            '#enableglobal: Sasha enables global gets on chat.',
            '#disableglobal: Sasha disables global gets on chat.',
            '#exportgroupsets: Sasha exports sets from chat.',
            'ADMIN',
            '#exportglobalsets: Sasha exports global sets.',
        },

        goodbyewelcome =
        {
            '🅿️ GOODBYEWELCOME',
            'Plugin for welcome and goodbye.',
            'MOD',
            'There are some markers that will be replaced when goodbye/welcome is sent: $chatid, $chatname, $chatusername, $rules, $userid, $firstname, $lastname, $printname, $username',
            '#getwelcome: Sasha sends welcome.',
            '#getgoodbye: Sasha sends goodbye.',
            '#previewwelcome: Sasha sends welcome sample.',
            '#previewgoodbye: Sasha sends goodbye sample.',
            '#setwelcome <text>: Sasha sets <text> as welcome.',
            '#setgoodbye <text>: Sasha sets <text> as goodbye.',
            '#unsetwelcome: Sasha removes welcome.',
            '#unsetgoodbye: Sasha removes goodbye.',
            '#setmemberswelcome <value>: Sasha after <value> members will send welcome, if zero welcome will not be sent anymore.',
            '#getmemberswelcome: Sasha sends value of users that are needed to get welcome.',
        },

        group_management =
        {
            '🅿️ GROUP_MANAGEMENT',
            'Plugin for the management of groups.',
            -- COMMON
            'USER',
            '#getwarn: Sasha sends max warns value.',
            '(#rules|sasha regole): Sasha sends group\'s rules.',
            '(#modlist|[sasha] lista mod): Sasha sends moderators list.',
            '#owner: Sasha sends owner\'s id.',
            '#admins [<reply>|<text>]: Sasha contacts admins',
            'MOD',
            '#type: Sasha sends group type.',
            '#updategroupinfo: Sasha updates group name and mods.',
            '(#setrules|sasha imposta regole) <text>: Sasha changes group\'s rules with <text>.',
            '#setwarn <value>: Sasha sets max warns to <value>, if zero warns will not work.',
            '#settings: Sasha sends group settings.',
            '#muteuser|voce <id>|<username>|<reply>|from: Sasha [un]mute specified user.',
            '(#muteslist|lista muti): Sasha sends muted parameters list.',
            '(#mutelist|lista utenti muti): Sasha sends muted users list.',
            '(#link|sasha link): Sasha sends group\'s link.',
            '#setflood <value>: Sasha sets <value> as max flood.',
            '(#lock|[sasha] blocca) arabic|bot|flood|leave|link|member|rtl|spam|strict: Sasha locks specified parameter.',
            '(#unlock|[sasha] sblocca) arabic|bot|flood|leave|link|member|rtl|spam|strict: Sasha unlocks specified parameter.',
            'OWNER',
            '#log: Sasha sends a file that contains group/realm log.',
            '(#setlink|sasha imposta link) <link>: Sasha saves <link> as group\'s link.',
            '(#unsetlink|sasha elimina link): Sasha deletes the saved link.',
            '(#promote|[sasha] promuovi) <id>|<username>|<reply>|from: Sasha promotes to mod specified user.',
            '(#demote|[sasha] degrada) <id>|<username>|<reply>|from: Sasha demotes from mod specified user.',
            '#mute|silenzia all|audio|contact|document|gif|location|photo|sticker|text|tgservice|video|voice: Sasha mute specified parameter.',
            '#unmute|ripristina all|audio|contact|document|gif|location|photo|sticker|text|tgservice|video|voice: Sasha unmute specified parameter.',
            '#setowner <id>|<username>|<reply>|from: Sasha sets specified user as owner.',
            '#clean modlist|rules: Sasha cleans specified parameter.',
            '(#getadmins|[sasha] lista admin): Sasha sends telegram\'s administrators list.',
            'ADMIN',
            '#add: Sasha adds the group in which you are.',
            '#rem: Sasha removes the group in which you are.',
            'ex INGROUP.LUA',
            '#add realm: Sasha adds realm.',
            '#rem realm: Sasha removes realm.',
            'ex INPM.LUA',
            '#allchats: Sasha sends a list of all chats.',
            '#allchatlist: Sasha sends a file with a list of all chats.',
            'REALM',
            '#setgpowner <group_id> <user_id>: Sasha sets <user_id> as owner of <group_id>.',
            '(#setrules|sasha imposta regole) <group_id> <text>: Sasha changes <group_id>\'s rules with <text>.',
            '(#lock|[sasha] blocca) <group_id> arabic|bot|flood|leave|link|member|rtl|spam|strict: Sasha locks <group_id>\'s specified setting.',
            '(#unlock|[sasha] sblocca) <group_id> arabic|bot|flood|leave|link|member|rtl|spam|strict: Sasha unlocks <group_id>\'s specified setting.',
            '#settings <group_id>: Sasha sends <group_id>\'s settings.',
            '#supersettings <supergroup_id>: Sasha sends <supergroup_id>\'s settings.',
            '#rem <group_id>: Sasha removes group.',
            '#list admins|groups|realms: Sasha sends list of specified parameter.',
            'SUDO',
            '#addadmin <user_id>|<username>: Sasha promotes specified user to administrator.',
            '#removeadmin <user_id>|<username>: Sasha demotes specified user from administrator.',
        },

        help =
        {
            '🅿️ HELP',
            'Plugin to help users with commands, USE IT!',
            'USER',
            '(#sudolist|sasha lista sudo): Sasha sends sudo list.',
            '(#help|sasha aiuto): Sasha sends a list of plugins.',
            '(#help|sasha aiuto) <plugin_name>|<plugin_number>: Sasha sends help of specified plugin.',
            '(#helpall|sasha aiuto tutto): Sasha sends help of all plugins.',
            '(#syntax|sasha sintassi) <filter>: Sasha sends syntax of all commands that matches with <filter>.',
            '(#syntaxall|sasha sintassi tutto): Sasha sends syntax of all commands of all plugins.',
        },

        info =
        {
            '🅿️ INFO',
            'Plugin to obtain info.',
            'USER',
            '#getrank|rango [<id>|<username>|<reply>]: Sasha sends rank of specified user.',
            '#whoami: Sasha sends user\'s info.',
            '(#info|[sasha] info): Sasha sends user\'s info and chat\'s info or her info.',
            '#ishere <id>|<username>|<reply>|from: Sasha says if the specified user is in the group.',
            'MOD',
            '(#info|[sasha] info) <id>|<username>|<reply>|from: Sasha sends info of specified parameter.',
            'ADMIN',
            '(#grouplink|[sasha] link gruppo) <group_id>: Sasha sends link of specified group.',
        },

        interact =
        {
            '🅿️ INTERACT',
            'Plugin for the interaction with users.',
            'MOD',
            '(#echo|sasha ripeti) [<reply>]<text>: Sasha repeat <text>, if in reply of a message she replies to that message.',
        },

        likecounter =
        {
            '🅿️ LIKECOUNTER',
            'Plugin for the management of likes.',
            'USER',
            '#like|#1up <id>|<username>|<reply>|from: Sasha adds a like to specified user.',
            '#dislike|#1down <id>|<username>|<reply>|from: Sasha removes a like from specified user.',
            '#likes: Sasha sends the likes leaderboard.',
            'SUDO',
            '#createlikesdb:  Sasha creates likecounter database.',
            '#addlikes <id> <value>: Sasha adds <value> likes to specified user.',
            '#remlikes <id> <value>: Sasha removes <value> likes to specified user.',
        },

        lua_exec =
        {
            '🅿️ LUA_EXEC',
            'Plugin for executing LUA code.',
            'SUDO',
            '#lua <command>: Sasha executes <command>.',
        },

        me =
        {
            '🅿️ ME',
            'Plugin to know number of sent messages.',
            'USER',
            '#me: Sasha tells you how many messages you\'ve sent.',
        },

        onservice =
        {
            '🅿️ ONSERVICE',
            'Plugin to make Sasha leave a group.',
            'ADMIN',
            '(#leave|sasha abbandona) [<group_id>]: Sasha leaves the group.',
        },

        plugins =
        {
            '🅿️ PLUGINS',
            'Plugin to enable or disable plugins.',
            'OWNER',
            '(#plugins|[sasha] lista plugins): Sasha sends a list of all plugins.',
            '(#disabledlist|([sasha] lista disabilitati|disattivati)): Sasha sends disabled plugins list.',
            '(#enable|[sasha] abilita|[sasha] attiva) <plugin> chat: Sasha re enables <plugin> on this chat.',
            '(#disable|[sasha] disabilita|[sasha] disattiva) <plugin> chat: Sasha disables <plugin> on this chat.',
            'SUDO',
            '(#enable|[sasha] abilita|[sasha] attiva) <plugin> [chat]: Sasha enables <plugin>, if specified just on chat.',
            '(#disable|[sasha] disabilita|[sasha] disattiva) <plugin> [chat]: Sasha disables <plugin>, if specified just on chat.',
            '(#reload|[sasha] ricarica): Sasha reloads all plugins.',
        },

        pokedex =
        {
            '🅿️ POKEDEX',
            'Plugin to obtain info on pokémons.',
            'USER',
            '#pokedex|#pokemon <name>|<id>: Sasha searches specified pokemon and sends its info.',
        },

        qr =
        {
            '🅿️ QR',
            'Plugin to create QR Codes.',
            'USER',
            '(#qr|sasha qr) ["<background_color>" "<data_color>"] <text>: Sasha creates QR Code of <text>, if specified it colors QR Code.',
            'Colors can be specified as follows:',
            'Text => red|green|blue|purple|black|white|gray.',
            'Hexadecimal => ("a56729" è marrone).',
            'Decimal => ("255-192-203" è rosa).',
        },

        reactions =
        {
            '🅿️ REACTIONS',
            'Plugin to make Sasha reacts.',
            'MOD',
            '#typing: Sasha pretends to write.',
            '#upload_photo: Sasha pretends to upload a photo.',
            '#record_video: Sasha pretends to record a video.',
            '#upload_video: Sasha pretends to upload a video.',
            '#record_audio: Sasha pretends to record an audio.',
            '#upload_audio: Sasha pretends to upload an audio.',
            '#upload_document: Sasha pretends to upload a document.',
            '#find_location: Sasha pretends to send a location.',
        },

        set =
        {
            '🅿️ SET',
            'Plugin to save things.',
            'MOD',
            '(#set|[sasha] setta) <var_name> <text>: Sasha saves <text> as answer to <var_name>.',
            '(#setmedia|[sasha] setta media) <var_name>: Sasha saves the media (photo, video, audio, voice note, document, sticker) in <reply> as answer to <var_name>.',
            'ADMIN',
            '#setglobal <var_name> <text>: Sasha globally saves <text> as answer to <var_name>.',
        },

        shout =
        {
            '🅿️ SHOUT',
            'Plugin to shout words.',
            'USER',
            '(#shout|[sasha] grida|[sasha] urla) <text>: Sasha "shouts" <text>.',
        },

        stats =
        {
            '🅿️ STATS',
            'Plugin to obtain stats on groups and Sasha.',
            'USER',
            '[#]aisashabot: Sasha sends her description.',
            'MOD',
            '(#stats|#messages): Sasha sends chat\'s stats.',
            '(#cleanstats|#cleanmessages): Sasha cleans chat\'s stats.',
            '(#statslist|#messageslist): Sasha sends file with chat\'s stats.',
            'ADMIN',
            '(#stats|#messages) group <group_id>: Sasha sends <group_id>\'s stats.',
            '(#cleanstats|#cleanmessages) group <group_id>: Sasha cleans <group_id>\'s stats.',
            '(#statslist|#messageslist) group <group_id>: Sasha sends file with <group_id>\'s stats.',
        },

        strings =
        {
            '🅿️ STRINGS',
            'Plugin for the management of Sasha\'s languages.',
            'USER',
            '(#setlang|lingua) (it|en): Sasha sets the language she has to talk (works just in private with the user).',
            'OWNER',
            '(#setlang|lingua) (it|en): Sasha sets the language she has to talk in this group.',
            'SUDO',
            '(#reloadstrings|[sasha] aggiorna stringhe): Sasha updates strings.',
        },

        tex =
        {
            '🅿️ TEX',
            'Plugin to create equations.',
            'USER',
            '(#tex|[sasha] equazione) <equation>: Sasha converts <equation> in image.',
        },

        tgcli_to_api_migration =
        {
            '🅿️ TGCLI_TO_API_MIGRATION',
            'Plugin for the migration from tgcli.',
            'OWNER',
            '#migrate: Sasha migrates group settings, bans, variables set and likes.',
            'SUDO',
            '#sudomigrate: Sasha migrates databases and global sets.',
        },

        unset =
        {
            '🅿️ UNSET',
            'Plugin to delete things saved with SET.',
            'MOD',
            '(#unset|[sasha] unsetta) <var_name>: Sasha deletes <var_name>.',
            'ADMIN',
            '#unsetglobal <var_name>: Sasha globally deletes <var_name>.',
        },

        urbandictionary =
        {
            '🅿️ URBANDICTIONARY',
            'Plugin for the interaction with the Urban Dictionary.',
            'USER',
            '(#urbandictionary|#urban|#ud|[sasha] urban|[sasha] ud) <text>: Sasha searches <text> in the Urban Dictionary.',
        },

        webshot =
        {
            '🅿️ WEBSHOT',
            'Plugin to make screenshots of websites.',
            'MOD',
            '(#webshot|[sasha] webshotta) <url> [<size>]: Sasha does a screenshot of <url> and sends it, if <size> is specified it sends of that dimension.',
            'Size can be:',
            'T: (120 x 90px)',
            'S: (200 x 150px)',
            'E: (320 x 240px)',
            'N: (400 x 300px)',
            'M: (640 x 480px)',
            'L: (800 x 600px)',
            'X: (1024 x 768px)',
            'Nmob: (480 x 800px)',
            'ADMIN',
            'F: Full page (can be a very long process)',
            'Fmob: Full page (can be a long process)',
        },

        whitelist =
        {
            '🅿️ WHITELIST',
            'Plugin for the management of the whitelist.',
            'ADMIN',
            '#whitelist [<id>|<username>|<reply>]: Sasha adds|removes specified user to|from whitelist, if nothing is specified Sasha sends the whitelist.',
            '#clean whitelist: Sasha cleans whitelist.',
        },
    },
}